package platform

// Code generated by TestAggregateSpeedResults at 2026-08-17 18:14:12;
// 该文件通过聚合 test_output/speed_results*.csv 生成，用于提供额外精选测速 URL。

var fastSpeedTestURLs = []string{
	"https://awscli.amazonaws.com/AWSCLIV2.msi",                                                     // avg: 3571.10 KB/s, samples: 5, errors: 2
	"https://cachefly.cachefly.net/300mb.test",                                                      // avg: 2848.73 KB/s, samples: 7, errors: 0
	"https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.15.0-linux-x86_64.tar.gz", // avg: 2156.06 KB/s, samples: 5, errors: 2
	"https://updates.cdn-apple.com/2025FallFCS/fullrestores/089-12066/4F86CB11-E6FA-47CB-96A8-527A4CBD9273/iPhone18,3_26.1_23B85_Restore.ipsw", // avg: 1827.91 KB/s, samples: 6, errors: 1
	"https://hnd-jp-ping.vultr.com/vultr.com.1000MB.bin",                                                        // avg: 1819.85 KB/s, samples: 5, errors: 2
	"https://hkg.download.datapacket.com/1000mb.bin",                                                            // avg: 1747.12 KB/s, samples: 6, errors: 1
	"https://dl.google.com/chrome/install/ChromeStandaloneSetup64.exe",                                          // avg: 1684.77 KB/s, samples: 6, errors: 1
	"https://sgp.download.datapacket.com/1000mb.bin",                                                            // avg: 1502.21 KB/s, samples: 7, errors: 0
	"https://get.enterprisedb.com/postgresql/postgresql-16.3-1-windows-x64.exe",                                 // avg: 1478.22 KB/s, samples: 6, errors: 1
	"https://fra-de-ping.vultr.com/vultr.com.1000MB.bin",                                                        // avg: 1329.21 KB/s, samples: 6, errors: 1
	"https://download.gimp.org/mirror/pub/gimp/v3.0/windows/gimp-3.0.0-setup.exe",                               // avg: 1262.27 KB/s, samples: 5, errors: 2
	"https://tyo.download.datapacket.com/1000mb.bin",                                                            // avg: 1257.83 KB/s, samples: 7, errors: 0
	"https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda_12.5.1_555.85_windows.exe", // avg: 1174.86 KB/s, samples: 6, errors: 1
	"https://nodejs.org/dist/v22.13.1/node-v22.13.1-x64.msi",                                                    // avg: 1143.49 KB/s, samples: 6, errors: 1
	"https://ash.download.datapacket.com/1000mb.bin",                                                            // avg: 1130.94 KB/s, samples: 6, errors: 1
}
